# Generated by Django 5.1.3 on 2025-03-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformpermission',
            name='platform',
        ),
        migrations.AddField(
            model_name='platformpermission',
            name='platform_application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='permission_gateway.platformapplication'),
            preserve_default=False,
        ),
    ]
