# Generated by Django 5.1.3 on 2025-03-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_gateway', '0002_remove_platformpermission_platform_and_more'),
        ('uac', '0006_remove_team_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlatformPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission_gateway.platformpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uac.profile')),
            ],
        ),
    ]
